---
# Gentoo package atoms. Verify and adjust USE flags as needed.
packages:
  - app-admin/ansible
  - app-admin/ansible-lint
  - app-shells/bash-completion
  - sys-process/bpytop
  - app-arch/bzip2
  - dev-build/cmake
  - app-misc/fastfetch
  - sys-fs/fswatch
  - dev-vcs/git
  - dev-vcs/git-filter-repo
  - dev-lang/go
  - net-misc/iperf
  - net-ftp/lftp
  - dev-libs/libzip
  - dev-vcs/mercurial
  - app-editors/nano
  - app-editors/neovim
  - dev-build/ninja
  - net-analyzer/nmap
  - dev-lang/php
  - dev-util/pkgconf
  - app-admin/pwgen
  - dev-lang/python-exec
  - dev-lang/rust
  - media-libs/libsdl2
  - dev-vcs/subversion
  - dev-lang/zig
  - sys-libs/zlib
  - app-shells/zsh
  - app-shells/zsh-completions
